//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated from a template.
//
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.CodeDom.Compiler;
using System.Diagnostics;

namespace Services.Data
{
    [GeneratedCode("Entity","0.9"), DebuggerNonUserCode]
    public partial class User
    {
        #region Primitive Properties
    
    	public virtual string Login
    	{
    		get;
    		set;
    	}
    
    	public virtual string Email
    	{
    		get;
    		set;
    	}
    
    	public virtual byte[] Password
    	{
    		get;
    		set;
    	}
    
    	public virtual byte[] Salt
    	{
    		get;
    		set;
    	}
    
    	public virtual string FirstName
    	{
    		get;
    		set;
    	}
    
    	public virtual string LastName
    	{
    		get;
    		set;
    	}
    
    	public virtual System.DateTime RegistrationDate
    	{
    		get;
    		set;
    	}
    
    	public virtual System.DateTime LastUpdateDate
    	{
    		get;
    		set;
    	}
    
    	public virtual string AvaUrl
    	{
    		get;
    		set;
    	}
    
    	public virtual byte Status
    	{
    		get;
    		set;
    	}

        #endregion
    }
}
