[assembly: System.Reflection.AssemblyVersion("1.0.0.0")]
[assembly: System.Reflection.AssemblyFileVersion("1.0.311.0")]
[assembly: System.Reflection.AssemblyCopyright("(c) SkyShoot team.")]
[assembly: System.Reflection.AssemblyProduct("SkyShoot")]
[assembly: System.Reflection.AssemblyCompany("SkyShoot team")]
[assembly: System.Reflection.AssemblyDefaultAlias("SkyShoot.XNA.Lite.dll")]
[assembly: System.Reflection.AssemblyTitle("SkyShoot.XNA.Lite.dll")]
[assembly: System.Reflection.AssemblyDescription("SkyShoot.XNA.Lite.dll")]
[assembly: System.CLSCompliant(true)]
