//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated from a template.
//
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// Architectural overview and usage guide: 
// http://blogofrab.blogspot.com/2010/08/maintenance-free-mocking-for-unit.html
//------------------------------------------------------------------------------
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Common;
using System;
using System.CodeDom.Compiler;
using System.Diagnostics;

namespace Services.Data
{
    /// <summary>
    /// The interface for the specialised object context. This contains all of
    /// the <code>ObjectSet</code> properties that are implemented in both the
    /// functional context class and the mock context class.
    /// </summary>
    [GeneratedCode("Entity","0.9")]
    public partial interface IEntities
    {
    	IObjectSet<Administrator> Administrators { get; }
    	IObjectSet<User> Users { get; }
    	void Dispose();
    	
    	int SaveChanges();
    	
    	void UseTracking(bool enable);
    }
}
